parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Symfony\Component\Routing\RequestContext:
    calls:
      - [ setBaseUrl, [ '' ] ]
      - [ setHost, [ '%env(APP_HOST)%' ] ]
      - [ setScheme, [ '%env(APP_SCHEME)%' ] ]

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  # Inyección de dependencias para los Comandos.
  App\Command\MakeDCrudCommand\MakeDCrudCommand:
    arguments:
      $em: '@doctrine.orm.entity_manager'
      $projectDir: '%kernel.project_dir%'
    tags: [ 'console.command' ]

  App\Command\ImportAmazonProductsCommand\ImportAmazonProductsCommand:
    arguments:
      $productImporter: '@App\Service\Platform\Amazon\Importer\AmazonProductImporterInterface'
      $projectDir: '%kernel.project_dir%'
    tags: [ 'console.command' ]

  App\Command\ExportAmazonProductsCommand\ExportAmazonProductsCommand:
    arguments:
      $productExporter: '@App\Service\Platform\Amazon\Exporter\AmazonProductExporterInterface'
      $projectDir: '%kernel.project_dir%'
    tags: [ 'console.command' ]

  # Inyección de dependencias para los Servicios de Amazon - Importación
  App\Service\Platform\Amazon\Importer\AmazonProductImporterInterface:
    alias: App\Service\Platform\Amazon\Importer\AmazonProductImporter

  App\Service\Platform\Amazon\Importer\AmazonProductImporter:
    arguments:
      $entityManager: '@doctrine.orm.entity_manager'
      $productRepository: '@App\Repository\ProductRepository'
      $dataProcessor: '@App\Service\Platform\Amazon\Processor\AmazonDataProcessorInterface'
      $logger: '@logger'

  # Inyección de dependencias para los Servicios de Amazon - Exportación
  App\Service\Platform\Amazon\Exporter\AmazonProductExporterInterface:
    alias: App\Service\Platform\Amazon\Exporter\AmazonProductExporter

  App\Service\Platform\Amazon\Exporter\AmazonProductExporter:
    arguments:
      $productRepository: '@App\Repository\ProductRepository'
      $dataProcessor: '@App\Service\Platform\Amazon\Processor\AmazonDataProcessorInterface'
      $logger: '@logger'

  # Inyección de dependencias para los Servicios de Amazon - Procesamiento de datos
  App\Service\Platform\Amazon\Processor\AmazonDataProcessorInterface:
    alias: App\Service\Platform\Amazon\Processor\AmazonDataProcessor

  App\Service\Platform\Amazon\Processor\AmazonDataProcessor:
    arguments:
      $transformer: '@App\Service\Platform\Amazon\Transformer\AmazonProductTransformerInterface'
      $logger: '@logger'

  # Inyección de dependencias para los Servicios de Amazon - Transformación
  App\Service\Platform\Amazon\Transformer\AmazonProductTransformerInterface:
    alias: App\Service\Platform\Amazon\Transformer\AmazonProductTransformer

  App\Service\Platform\Amazon\Transformer\AmazonProductTransformer:
    arguments:
      $logger: '@logger'

  # ===== NUEVOS SERVICIOS FRONTEND =====

  # Servicios Frontend - Interfaces y implementaciones
  App\Service\Platform\Amazon\Frontend\ProductQueryServiceInterface:
    alias: App\Service\Platform\Amazon\Frontend\ProductQueryService

  App\Service\Platform\Amazon\Frontend\ProductQueryService:
    arguments:
      $productRepository: '@App\Repository\ProductRepository'
      $logger: '@logger'

  App\Service\Platform\Amazon\Frontend\ScoreGeneratorServiceInterface:
    alias: App\Service\Platform\Amazon\Frontend\ScoreGeneratorService

  App\Service\Platform\Amazon\Frontend\ScoreGeneratorService:
    arguments:
      $logger: '@logger'

  App\Service\Platform\Amazon\Frontend\ProductFormatterServiceInterface:
    alias: App\Service\Platform\Amazon\Frontend\ProductFormatterService

  App\Service\Platform\Amazon\Frontend\ProductFormatterService:
    arguments:
      $logger: '@logger'

  App\Service\Platform\Amazon\Frontend\RankingFacadeServiceInterface:
    alias: App\Service\Platform\Amazon\Frontend\RankingFacadeService

  App\Service\Platform\Amazon\Frontend\RankingFacadeService:
    arguments:
      $productQueryService: '@App\Service\Platform\Amazon\Frontend\ProductQueryServiceInterface'
      $scoreGeneratorService: '@App\Service\Platform\Amazon\Frontend\ScoreGeneratorServiceInterface'
      $productFormatterService: '@App\Service\Platform\Amazon\Frontend\ProductFormatterServiceInterface'
      $logger: '@logger'