parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
  Symfony\Component\Routing\RequestContext:
    calls:
      - [ setBaseUrl, [ '' ] ]
      - [ setHost, [ '%env(APP_HOST)%' ] ]
      - [ setScheme, [ '%env(APP_SCHEME)%' ] ]
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
  App\Command\MakeDCrudCommand\MakeDCrudCommand:
    arguments:
      $em: '@doctrine.orm.entity_manager'
      $projectDir: '%kernel.project_dir%'
    tags: [ 'console.command' ]